### ISSUE TITLE
你好,请问能提供Unity滚动列表的源码参考吗

### ISSUE THREAD

**Issue by AfarMiss** [TonyTang1990/TonyTang1990.github.io#1]
您好,在博客的下面并未查看到源码链接,通过您的用户名在github搜索到的.
请问能提供Unity滚动列表的源码参考吗?
查看了大量的虚拟列表实现,觉得您的实现不错,希望能提供代码学习.

**Comment by TonyTang1990** [comment]
之前没开源，我改成public的仓库了，地址：https://github.com/TonyTang1990/ScrollContainer，博客github地址我后续补上。相对来说可能比不上Asset Store里的滚动列表，但可以作为参考学习，更多的学习个人推荐可以参考插件:FancyScrollView和ugui-super-scrollview-example这两个滚动插件。

**Comment by AfarMiss** [comment]
.刚看到您的回复,还没来得及仔细研究,注释写很多也很详细.
谢谢您提供的代码及参考建议.
特意去assetstore翻了一遍插件目录,有条件之后支持您的插件.
